database: none

services:
  - type: web
    name: menu-digital
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind :$PORT
    healthCheckPath: /
